; PlatformIO Project Configuration File for ezpropkit
; Target: Adafruit RP2040 Prop-Maker Feather (SKU 5768)

[platformio]
default_envs = feather_rp2040
description = ezpropkit: Lua & C Firmware for Adafruit RP2040 Prop-Maker Feather

[env:feather_rp2040]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = adafruit_feather
framework = arduino
board_build.core = earlephilhower
board_build.filesystem_size = 6m
board_build.f_cpu = 200000000L

; RP2040 200 MHz Overclock, -O3 Optimization, and TinyUSB
build_flags =
    -O3
    -DUSE_TINYUSB
    -Iinclude
    -Isrc

; Upstream Libraries
lib_deps =
    mischief/lua
    https://github.com/earlephilhower/BackgroundAudio.git
    adafruit/Adafruit NeoPixel
    adafruit/Adafruit LIS3DH
    adafruit/Adafruit Unified Sensor

monitor_speed = 115200
upload_protocol = picotool
